env_lib: "safety_gym"
env_id: Safexp-PointGoal1-v0
use_cost_indicator: False
device: "cpu"

# env_lib: "safety_gymnasium"
# env_id: SafetyPointGoal1-v0
# use_cost_indicator: False
# device: "cpu"

# env_lib: "gymnasium"
# env_id: merge-v1

ac_kwargs:
  hid_dim: 64
  activation: "tanh"
  
seed: 0
epochs: 1000
steps_per_epoch: 30000
max_ep_len: 1000

gamma: 0.99
lamda: 0.97
clip_ratio: 0.2
target_kl: 0.01

lagrange_init: 0.0
cost_limit: 0

pi_lr: 0.0003
vf_lr: 0.001
lagrange_lr: 0.0003

train_pi_iters: 80
train_v_iters: 80
train_lagrange_iters: 5