env_lib: "safety_gymnasium"
env_id: SafetyPointGoal1-v0  # safety_gymnasium
use_cost_indicator: False
device: "cuda"

# env_lib: "gymnasium"
# env_id: merge-v1  # highway_env

ac_kwargs:
  hid_dim: 64
  activation: "tanh"

seed: 0
epochs: 1000
steps_per_epoch: 30000
max_ep_len: 1000

gamma: 0.99
lamda: 0.97
clip_ratio: 0.2
target_kl: 0.01

pi_lr: 0.0003
vf_lr: 0.001

train_pi_iters: 80
train_v_iters: 80