env_lib: "safety_gymnasium"
env_id: SafetyPointGoal1-v0  # safety_gymnasium
use_cost_indicator: False
device: "cpu"

# env_lib: "gymnasium"
# env_id: merge-v1  # highway_env

ac_kwargs:
  hid_dim: 64
  activation: "tanh"
  auto_alpha: True

seed: 0
epochs: 1500
steps_per_epoch: 2000
max_ep_len: 1000
replay_size: 1000000
batch_size: 256

start_steps: 10000

gamma: 0.99
polyak: 0.995

pi_lr: 0.001
q_lr: 0.001
alpha_lr: 0.001

update_iters: 1
policy_delay: 2
num_test_episodes: 1